---
machine:
  environment:
    CODECLIMATE_REPO_TOKEN: ab24b326dac817e772c5246823b67af66e2358e51134c33e20aaf7fb228088b0
    
engines:
  duplication:
    enabled: false
    config:
      languages:
      - python
  fixme:
    enabled: true
  pep8:
    enabled: true
  radon:
    enabled: true
ratings:
  paths:
  - "**.py"
exclude_paths:
  - "*docs/*"
  - "*examples/*"
  - "*/site-packages/*"
  - "*markupsafe/*"
  - "*psycopg2/*"
  - "*six.py*"
  - "*sqlalchemy/*"
  - "*werkzeug/*"
  - "*stringprep.py*"
  - "*uuid.py*"
  - "*ctypes/*"
  - "*decimal.py*"
  - "*encodings/*"
  - "*hmac.py*"
  - "*asyncio/*"
  - "*concurrent/*"
  - "*multiprocessing/*"
  - "*mimetypes.py*"
  - "*numbers.py*"
  - "*pydoc.py*"
  - "*http/*"
  - "*app/__init__.py*"
  - "*app/__init__.py*"
  - "*app/config.py*"
  - "*app/model/*"
  - "*test/*"
  - "*html/*"
  - "*_bootlocale.py*"
  - "*typing.py*"
  - 